GuiCoutoSt/feeling.

- src/services/api.js
foi cria o arquivo api.js com a url base
> feat: api.js file ready

- src/index.js
> fix: Adding the BrowserRouter

- src/pages/Home/HomeBottom.jsx
- src/pages/Home/HomeTop.jsx
- src/pages/Home/styles.js
> fix: Refactoring the home page

- src/pages/Home/HomeBottom.jsx
- src/pages/Home/HomeTop.jsx
Adicionando animações à homepage.
> Feature homepage bottom

- src/components/Input/ControlledInput.jsx
- src/pages/Login/LoginForm.jsx
- src/pages/Login/LoginImage.jsx
- src/pages/Login/index.jsx
- src/pages/SignUp/SignupForm.jsx
- src/pages/SignUp/SignupImage.jsx
- src/pages/SignUp/index.jsx
- src/routes/index.jsx
Refatoração dos tamanhos do SignIn e SignUp
> Feat refactoring

- src/components/Card/PhraseCard.jsx
- src/components/Modal/NewComment.jsx
- src/pages/Comments/FellasComments.jsx
- src/pages/Comments/index.jsx
foi criado o modal para adicionar novo comentário
> feat: new comment modal ok

- src/provider/PhrasesContext/index.jsx
> fix: modify endpoint api in search

- src/components/Card/PhraseCard.jsx
- src/components/Header/index.jsx
- src/components/Modal/NewComment.jsx
- src/pages/Comments/FellasComments.jsx
- src/pages/Dashboard/DashboardContent.jsx
a página de comentarios da galera esta pronta e também o modal de novo comentário, porém, ainda não estão ligados ao server
> Feature galera modal

- src/provider/PhrasesContext/index.jsx
Corrige solicitação api no search com os novas descrições das propriedades em phrases.
> fix: modify properties of phrases in context

- src/components/Header/Search.jsx
- src/pages/Login/LoginForm.jsx
- src/provider/PhrasesContext/index.jsx
Consertando o bug de hooks exhaustive deps
> fix: Fixing the hooks exhaustive deps bug

- src/pages/Favorites/index.jsx
> Feature favorites

- src/pages/Dashboard/index.jsx
Requisição para saudar o usuário
> feat: saudaçao ao usuario

- src/components/Input/ControlledInput.jsx
- src/pages/Login/LoginForm.jsx
- src/pages/Login/index.jsx
- src/pages/SignUp/SignupForm.jsx
- src/pages/SignUp/index.jsx
Resolvendo o bug do yup e refatorando uma parte da estilização
> fix: Fixing the yup bug + Refactoring the signup and login styling

- src/components/Card/FavoriteCard.jsx
- src/pages/Phrases/GridSearch.jsx
- src/pages/Phrases/index.jsx
- src/provider/PhrasesContext/index.jsx
Acrescenta parcial da página Phrases e componente card Favorite para ser utilizado como base. Ainda falta algumas estilizações.
> feat: add page Phrases

- src/components/Card/MyCommentCard.jsx
- src/components/Modal/EditComment.jsx
- src/pages/MyComments/index.jsx
- src/provider/CommentsProvider/index.jsx
- src/provider/index.jsx
- src/routes/index.jsx
Requisições página Meus comentários
> Feat my comment request

- src/components/Card/FavoriteCard.jsx
- src/components/Header/Menu.jsx
- src/components/Header/index.jsx
- src/styles/theme.js
Adiciona tooltips e faz uma estilização padrão para o tooltip no theme global para que o tooltip siga o mesmo padrão em todo o site.
> feat: add tooltips

- src/components/Card/FavoriteCard.jsx
- src/pages/Favorites/index.jsx
- src/provider/AuthContext/index.jsx
- src/provider/CommentsProvider/index.jsx
- src/provider/PhrasesContext/index.jsx
Funções de adicionar e deletar frase do favoritos
> feat: function add and delete favorite

- src/components/Modal/ModalCard.jsx
- src/pages/Dashboard/DashboardContent.jsx
- src/provider/AuthContext/index.jsx
Toast error login 
Dashboard name
> fix: toast error, dashboard name

- src/components/Input/ControlledInput.jsx
- src/pages/Home/HomeWelcome.jsx
- src/pages/Login/LoginForm.jsx
- src/pages/Login/index.jsx
- src/pages/SignUp/SignupForm.jsx
- src/pages/SignUp/index.jsx
- src/routes/index.jsx
Adicionando algumas imagens ao app
> Feat animations

- src/provider/CommentsProvider/index.jsx
Faltou incluir um return dentro de RandomPhrase. Adicionado.
> fix: add return in randomPhrase
